name: CI
on: [pull_request]
jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  test_core:
    name: "test:core"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn workspace @model-ts/core test

  test_eventbridge:
    name: "test:eventbridge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Core
        run: yarn workspace @model-ts/core build

      - name: Test
        run: yarn workspace @model-ts/eventbridge test

  test_dynamodb:
    name: "test:dynamodb"
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Core
        run: yarn workspace @model-ts/core build

      - name: Test
        run: yarn workspace @model-ts/dynamodb test

      - name: Test (memory)
        run: yarn workspace @model-ts/dynamodb test:memory
